### ISSUE TITLE
Explorer display is very slow

### ISSUE THREAD

**Issue by ryo-opening-line** [symbol/symbol-explorer#766]
Explorer display is very slow.

I think the explorer of testnet as follows is very slow:
http://explorer.testnet.symboldev.network/

It seems to be taking over 20 secs for the top page to be fully displayed.

I would like to see improvement.

Thanks!

**Comment by AnthonyLaw** [comment]
did it happen to your machine every time?

One of the reasons I can think of is that we are pulling a lot of data from the different API endpoints.

**Comment by jabo38** [comment]
This isn't just happening on the testnet explorer, I regularly experience it on the main net explorer which I use everyday and it makes the experience problematic at times. 

I'm afraid some people don't have 10-20 seconds to wait for it to load and think it is broken and move on.

**Comment by jabo38** [comment]
I just made a video, and it took over 2 minutes to load the page. I have tested both Safari and Firefox and both are affected. I would upload the video but trying to figure out how to get a 2 minute video to Github from my phone without breaking the internet :-)

**Comment by OlegMakarenko** [comment]
Thank you. Fixed in **v1.1.1**
