### ISSUE TITLE
https support for the testnet site

### ISSUE THREAD

**Issue by ryo-opening-line** [symbol/symbol-explorer#767]
Currently, the testnet explorer supports only http.
http://explorer.testnet.symboldev.network/

There are some environments where http sites cannot be displayed.
So it would be better to support also https.

Thanks!

**Comment by AnthonyLaw** [comment]
thanks for report this.

@Wayonb if you have time, can look at it :)

**Comment by gimer** [comment]
what's the current status of this ^^

**Comment by Wayonb** [comment]
@AnthonyLaw Sorry I missed this. Did you need anything from me?

**Comment by AnthonyLaw** [comment]
@Wayonb Nope from now, In early, I was thinking of just install the SSL/TLS on our Explorer web server should be fine, But It may have the CORS issue because our API nodes are not using `Https`

after some discussion @OlegMakarenko is working on it.

**Comment by OlegMakarenko** [comment]
Thank you. Included in the latest version.
