### ISSUE TITLE
node map does not show all filtered nodes 

### ISSUE THREAD

**Issue by Jaguar0625** [symbol/symbol-explorer#841]
Nodes are filtered by "peer voting". Statistics indicated 44, which matches list below, but map only shows 5. 

![image](https://user-images.githubusercontent.com/4774992/111680281-70db6e00-87f8-11eb-9fd3-d9cfc4ff1330.png)

**Comment by OlegMakarenko** [comment]
Fixed in the Statistics Service _#58
