### ISSUE TITLE
Page Speed

### ISSUE THREAD

**Issue by ghost** [symbol/symbol-explorer#878]
The time that Explorer needs to load the page completely is more than 30 seconds.
Before that, only an blank screen is displayed. Nowadays this is an eternity.

If you try to open a "Transaction Hash" with "Open Link In New Tab" from a completely loaded Explorer page, it takes even more than 4 minutes. An blank screen is also displayed.

Browser - Firefox 78.9.0esr(64-bit)

**Comment by garm01** [comment]
Apparently this only occurs with this browser version.

**Comment by jabo38** [comment]
I use safari and have the same problem. I think we should re-open the issue.

**Comment by OlegMakarenko** [comment]
Thank you. Fixed in the latest version
