### ISSUE TITLE
Private networks show XYM when network currency is different

### ISSUE THREAD

**Issue by fboucquez** [symbol/symbol-explorer#920]
![image](https://user-images.githubusercontent.com/5390558/125305236-93901600-e304-11eb-89f7-c7031484e77e.png)

https://github.com/nemgrouplimited/symbol-explorer/blob/main/src/components/widgets/AccountBalanceWidget.vue#L98
https://github.com/nemgrouplimited/symbol-explorer/blob/main/src/store/account.js#L149

mosaicName is always undefined, resovled to hardcoded XYM. 

Should the component receive the data as parameters instead of the vuex storage? What if the user has other tokens than the network one?

**Comment by AnthonyLaw** [comment]
I think right now we only support XYM, do you think we can close this?\

**Comment by gimre-xymcity** [comment]
y, imo can be closed cc @Jaguar0625

**Comment by fboucquez** [comment]
I know we don't want to support other coins, but this issue is more like an implementation bug, params are not well provided. What if the user wants to show another mosaic in the big purple panel?
